package com.baixc.ucenter.model.admin;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.GrantedAuthorityImpl;
import org.springframework.security.core.userdetails.UserDetails;

public class Admins implements UserDetails, Serializable, Cloneable {
	
	private static final long serialVersionUID = -8097634475751877685L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.user_id
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.username
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String username;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.password
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.name
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.code
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.sex
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.dept
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String dept;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.position
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String position;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.mobile
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String mobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.email
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.reg_time
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private Date regTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.update_time
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_admins.enabled
     *
     * @ibatorgenerated Wed Jan 23 14:07:44 CST 2013
     */
    private Byte enabled;
    
    
    /**
     * 用户角色列表
     */
    private List<Roles> roles; 
    
    /**
     * 用户个性权限
     */
    private List<Modules> modules;
    

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.user_id
     *
     * @return the value of bai_admins.user_id
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.user_id
     *
     * @param userId the value for bai_admins.user_id
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.username
     *
     * @return the value of bai_admins.username
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.username
     *
     * @param username the value for bai_admins.username
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.password
     *
     * @return the value of bai_admins.password
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.password
     *
     * @param password the value for bai_admins.password
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.name
     *
     * @return the value of bai_admins.name
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.name
     *
     * @param name the value for bai_admins.name
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.code
     *
     * @return the value of bai_admins.code
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.code
     *
     * @param code the value for bai_admins.code
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.sex
     *
     * @return the value of bai_admins.sex
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.sex
     *
     * @param sex the value for bai_admins.sex
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getDept() {
		return dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.position
     *
     * @return the value of bai_admins.position
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.position
     *
     * @param position the value for bai_admins.position
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.mobile
     *
     * @return the value of bai_admins.mobile
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.mobile
     *
     * @param mobile the value for bai_admins.mobile
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.email
     *
     * @return the value of bai_admins.email
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.email
     *
     * @param email the value for bai_admins.email
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setEmail(String email) {
        this.email = email;
    }

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.reg_time
     *
     * @return the value of bai_admins.reg_time
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.reg_time
     *
     * @param regTime the value for bai_admins.reg_time
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.update_time
     *
     * @return the value of bai_admins.update_time
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.update_time
     *
     * @param updateTime the value for bai_admins.update_time
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_admins.enabled
     *
     * @return the value of bai_admins.enabled
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_admins.enabled
     *
     * @param enabled the value for bai_admins.enabled
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

	public List<Roles> getRoles() {
		return roles;
	}

	public void setRoles(List<Roles> roles) {
		this.roles = roles;
	}

	public List<Modules> getModules() {
		return modules;
	}

	public void setModules(List<Modules> modules) {
		this.modules = modules;
	}
	

	@Override
	public Collection<GrantedAuthority> getAuthorities() {
		Collection<GrantedAuthority> auths = new ArrayList<GrantedAuthority>();
		
		for(Roles roles : this.getRoles()){
			auths.add(new GrantedAuthorityImpl(roles.getRoleType()));
		}
		
		return auths;
	}

	@Override
	public boolean isAccountNonExpired() {
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		return true;
	}

	@Override
	public boolean isEnabled() {
		if(this.enabled>0){
			return true;
		}else{
			return false;
		}
	}

	/**
     * @return 创建并返回此对象的一个副本。
     * @throws CloneNotSupportedException
     */
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
    
}