package com.baixc.commons.model.configcenter;

public class Enums {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.id
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.biz
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private String biz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.group
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private String group;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.key
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private String key;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.text
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private String text;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.value
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private String value;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.sort
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private Integer sort;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.id
     *
     * @return the value of bai_enums.id
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.id
     *
     * @param id the value for bai_enums.id
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.biz
     *
     * @return the value of bai_enums.biz
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public String getBiz() {
        return biz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.biz
     *
     * @param biz the value for bai_enums.biz
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setBiz(String biz) {
        this.biz = biz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.group
     *
     * @return the value of bai_enums.group
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.group
     *
     * @param group the value for bai_enums.group
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setGroup(String group) {
        this.group = group;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.key
     *
     * @return the value of bai_enums.key
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.key
     *
     * @param key the value for bai_enums.key
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.text
     *
     * @return the value of bai_enums.text
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.text
     *
     * @param text the value for bai_enums.text
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.value
     *
     * @return the value of bai_enums.value
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.value
     *
     * @param value the value for bai_enums.value
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.sort
     *
     * @return the value of bai_enums.sort
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.sort
     *
     * @param sort the value for bai_enums.sort
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}