package com.baixc.commons.model.configcenter;

import java.io.Serializable;

public class Enums implements Serializable {

	private static final long serialVersionUID = -1042815365595198805L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.enums_id
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    private Integer enumsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.enums_type
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    private String enumsType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.enums_name
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    private String enumsName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.enums_text
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    private String enumsText;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column bai_enums.enums_remark
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    private String enumsRemark;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.enums_id
     *
     * @return the value of bai_enums.enums_id
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    public Integer getEnumsId() {
        return enumsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.enums_id
     *
     * @param enumsId the value for bai_enums.enums_id
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    public void setEnumsId(Integer enumsId) {
        this.enumsId = enumsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.enums_type
     *
     * @return the value of bai_enums.enums_type
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    public String getEnumsType() {
        return enumsType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.enums_type
     *
     * @param enumsType the value for bai_enums.enums_type
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    public void setEnumsType(String enumsType) {
        this.enumsType = enumsType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.enums_name
     *
     * @return the value of bai_enums.enums_name
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    public String getEnumsName() {
        return enumsName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.enums_name
     *
     * @param enumsName the value for bai_enums.enums_name
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    public void setEnumsName(String enumsName) {
        this.enumsName = enumsName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.enums_text
     *
     * @return the value of bai_enums.enums_text
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    public String getEnumsText() {
        return enumsText;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.enums_text
     *
     * @param enumsText the value for bai_enums.enums_text
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    public void setEnumsText(String enumsText) {
        this.enumsText = enumsText;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column bai_enums.enums_remark
     *
     * @return the value of bai_enums.enums_remark
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    public String getEnumsRemark() {
        return enumsRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column bai_enums.enums_remark
     *
     * @param enumsRemark the value for bai_enums.enums_remark
     *
     * @ibatorgenerated Tue Mar 20 17:48:05 CST 2012
     */
    public void setEnumsRemark(String enumsRemark) {
        this.enumsRemark = enumsRemark;
    }
}